model_name: skipgram
model_dir: weights/skipgram_WikiText2
dataset: WikiText2
data_dir: data/
optimizer: Adam
train_batch_size: 128
learning_rate: 0.025
epochs: 5
skipgram_n_words: 10
min_word_frequency: 50
neg_count: 5
embed_dimension: 5
n_print: 50
max_sequence_length: 256
